#!/bin/sh

ls kubectl || curl -LOC - https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

chmod +x ./kubectl
export PATH=`pwd`:$PATH
export KUBECONFIG=`pwd`/kubeconfig.yml

SECRET_NAMESPACE=storageos-operator
SECRET_NAME=storageos-api
STORAGE_SERVICE=storageos
STORAGE_SERVICE_NAMESPACE=storageos

export STORAGEOS_USERNAME=`kubectl get secret -n $SECRET_NAMESPACE $SECRET_NAME -o jsonpath="{.data.apiUsername}" | base64 --decode`
export STORAGEOS_PASSWORD=`kubectl get secret -n $SECRET_NAMESPACE $SECRET_NAME -o jsonpath="{.data.apiPassword}" | base64 --decode`
STORAGE_SERVICE_PORT=`kubectl get -n $STORAGE_SERVICE_NAMESPACE service/$STORAGE_SERVICE -o jsonpath='{.spec.ports[0].port}'`
export STORAGEOS_HOST="$STORAGE_SERVICE.$STORAGE_SERVICE_NAMESPACE.svc:$STORAGE_SERVICE_PORT"
export STORAGEOS_HOST="localhost:15706"

echo "to connect to storageos cluster: kubectl port-forward -n $STORAGE_SERVICE_NAMESPACE service/$STORAGE_SERVICE 15706:$STORAGE_SERVICE_PORT"
