apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageos-monitoring
  namespace: storageos-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storageos-monitoring
subjects:
  - kind: ServiceAccount
    name: storageos-monitoring
    namespace: storageos-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
  