apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: storageos-monitoring
  name: storageos-monitoring
  namespace: storageos-operator
spec:
  selector:
    matchLabels:
      app: storageos-monitoring
  template:
    metadata:
      labels:
        app: storageos-monitoring
    spec:
      containers:
      - name: storageos-monitoring
        image: ticapix/storageos-health-detector:latest
        # lifecycle:
        #   preStop:
        #     exec:
        #       command: ["/bin/sh","-c", "kubectl", "taint", "nodes", "$NODE_NAME", "StorageOSOnly:NoSchedule"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: STORAGEOS_USERNAME
          valueFrom:
            secretKeyRef:
              key: apiUsername
              name: storageos-api
        - name: STORAGEOS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: apiPassword
              name: storageos-api
        - name: STORAGEOS_HOST
          value: storageos.storageos.svc:5705
        imagePullPolicy: Always
      restartPolicy: Always
      serviceAccountName: storageos-monitoring
      terminationGracePeriodSeconds: 3600 # 1h to copy data between nodes
